"""inicial

Revision ID: c17c60a286a8
Revises: 
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'c17c60a286a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('login', sa.String(length=60), nullable=False),
    sa.Column('senha_hash', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('assembleia',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('abre_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fecha_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('categoria', sa.String(length=60), nullable=False),
    sa.Column('arquivo', sa.String(length=255), nullable=False),
    sa.Column('nome_original', sa.String(length=255), nullable=False),
    sa.Column('publico', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unidade',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bloco', sa.String(length=16), nullable=False),
    sa.Column('apto', sa.String(length=8), nullable=False),
    sa.Column('ativa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bloco', 'apto')
    )
    op.create_table('chamada',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('de_unidade_id', sa.UUID(), nullable=False),
    sa.Column('para_unidade_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='tocando', nullable=False),
    sa.Column('iniciada_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('encerrada_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['de_unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['para_unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chamada_de_unidade_id'), 'chamada', ['de_unidade_id'], unique=False)
    op.create_index(op.f('ix_chamada_para_unidade_id'), 'chamada', ['para_unidade_id'], unique=False)
    op.create_table('cobranca',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('unidade_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('valor', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), server_default='aberta', nullable=False),
    sa.Column('pago_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pix_copia_cola', sa.Text(), nullable=True),
    sa.Column('boleto_url', sa.String(length=500), nullable=True),
    sa.Column('gateway_ref', sa.String(length=120), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cobranca_unidade_id'), 'cobranca', ['unidade_id'], unique=False)
    op.create_index(op.f('ix_cobranca_vencimento'), 'cobranca', ['vencimento'], unique=False)
    op.create_table('morador',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('unidade_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=12), server_default='pendente', nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_morador_unidade_id'), 'morador', ['unidade_id'], unique=False)
    op.create_table('pauta',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('assembleia_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['assembleia_id'], ['assembleia.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pauta_assembleia_id'), 'pauta', ['assembleia_id'], unique=False)
    op.create_table('opcao',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('pauta_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['pauta_id'], ['pauta.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opcao_pauta_id'), 'opcao', ['pauta_id'], unique=False)
    op.create_table('push_subscription',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('morador_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['morador_id'], ['morador.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_index(op.f('ix_push_subscription_morador_id'), 'push_subscription', ['morador_id'], unique=False)
    op.create_table('voto',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('unidade_id', sa.UUID(), nullable=False),
    sa.Column('pauta_id', sa.UUID(), nullable=False),
    sa.Column('opcao_id', sa.UUID(), nullable=False),
    sa.Column('morador_id', sa.UUID(), nullable=False),
    sa.Column('inadimplente_no_voto', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('votado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['morador_id'], ['morador.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opcao_id'], ['opcao.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pauta_id'], ['pauta.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['unidade_id'], ['unidade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unidade_id', 'pauta_id')
    )
    op.create_index(op.f('ix_voto_morador_id'), 'voto', ['morador_id'], unique=False)
    op.create_index(op.f('ix_voto_opcao_id'), 'voto', ['opcao_id'], unique=False)
    op.create_index(op.f('ix_voto_pauta_id'), 'voto', ['pauta_id'], unique=False)
    op.create_index(op.f('ix_voto_unidade_id'), 'voto', ['unidade_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voto_unidade_id'), table_name='voto')
    op.drop_index(op.f('ix_voto_pauta_id'), table_name='voto')
    op.drop_index(op.f('ix_voto_opcao_id'), table_name='voto')
    op.drop_index(op.f('ix_voto_morador_id'), table_name='voto')
    op.drop_table('voto')
    op.drop_index(op.f('ix_push_subscription_morador_id'), table_name='push_subscription')
    op.drop_table('push_subscription')
    op.drop_index(op.f('ix_opcao_pauta_id'), table_name='opcao')
    op.drop_table('opcao')
    op.drop_index(op.f('ix_pauta_assembleia_id'), table_name='pauta')
    op.drop_table('pauta')
    op.drop_index(op.f('ix_morador_unidade_id'), table_name='morador')
    op.drop_table('morador')
    op.drop_index(op.f('ix_cobranca_vencimento'), table_name='cobranca')
    op.drop_index(op.f('ix_cobranca_unidade_id'), table_name='cobranca')
    op.drop_table('cobranca')
    op.drop_index(op.f('ix_chamada_para_unidade_id'), table_name='chamada')
    op.drop_index(op.f('ix_chamada_de_unidade_id'), table_name='chamada')
    op.drop_table('chamada')
    op.drop_table('unidade')
    op.drop_table('documento')
    op.drop_table('assembleia')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
